.TH <name> 1 "<meta_date>" "v<version>" "User commands"
.SH NAME
<name> \- <short_descr>
.SH SYNOPSIS
.nf
<synopsis>
.fi
.SH DESCRIPTION
<description>
.SH OPTIONS
<options>
.SH ARGUMENTS
<arguments>
.SH FILES
<files>
.SH
SECURITY
<security>
.SH EXAMPLES
<examples>
.SH REPORTING BUGS
Bugs and suggestions should be reported at: https://github.com/bashdroid/<name>/issues
.SH SEE ALSO
<seealso>
